[package]
name = "nec"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

[dependencies]
genco = "0.17.9"
relative-path = "1.9.3"
reqwest = { version = "0.12.7", features = ["blocking"] }
serde = "1.0.209"
serde_json = "1.0.127"
tempfile = "3.12.0"
zip = "2.2.0"
